#!/usr/bin/env bash
#Displays numbers from 1 to 100.

numero=1
while [ $numero -le 100 ]
do
    if [ $((numero % 15)) -eq 0 ]
    then
	echo "FizzBuzz"
    elif [ $((numero % 3)) -eq 0 ]
    then
	echo "Fizz"
    elif [ $((numero % 5)) -eq 0 ]
    then
	echo "Buzz"
    else
    echo "$numero"
    fi
    ((numero++))
done
